name: Deploy to WordPress Marketplace
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Plugin version to deploy'
        required: true
        default: ''
      dry-run:
        description: 'Perform dry run (no actual deployment)'
        required: false
        default: true
        type: boolean
      test-mode:
        description: 'Run in test mode'
        required: false
        default: false
        type: boolean
  push:
    branches:
      - main
    paths:
      - 'siteimprove/**'
      - '.github/workflows/deploy-wordpress.yml'
    tags:
      - 'wp-*' # Push events to matching wp-*, i.e. wp-2.0.8

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to WordPress Marketplace
        uses: ./.github/actions/deploy-to-wordpress
        with:
          version: ${{ github.event.inputs.version || github.ref_name }}
          plugin-slug: ${{ vars.WP_PLUGIN_SLUG || 'siteimprove' }}
          svn-username: ${{ github.event.inputs.test-mode && secrets.TEST_SVN_USERNAME || secrets.WP_SVN_USERNAME }}
          svn-password: ${{ github.event.inputs.test-mode && secrets.TEST_SVN_PASSWORD || secrets.WP_SVN_PASSWORD }}
          svn-url: ${{ vars.WP_SVN_URL || 'https://plugins.svn.wordpress.org/siteimprove/' }}
          assets-dir: ${{ vars.WP_ASSETS_DIR || 'wordpress-assets' }}
          dry-run: ${{ github.event.inputs.dry-run || false }}
          test-mode: ${{ github.event.inputs.test-mode || false }}
